.TH "Referencia del directorio C:/Users/carme/OneDrive/Desktop/cuarto/Electronica Programable" 3 "guia1_ej2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio C:/Users/carme/OneDrive/Desktop/cuarto/Electronica Programable
.SH SYNOPSIS
.br
.PP
.SS "Directorios"

.in +1c
.ti -1c
.RI "directorio \fBRepositorios\fP"
.br
.in -1c
