.TH "Referencia del directorio C:/Users/carme/OneDrive/Desktop/cuarto/Electronica Programable/Repositorios/Dominguez_2C_2025/firmware/projects/guia1_ej2" 3 "guia1_ej2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio C:/Users/carme/OneDrive/Desktop/cuarto/Electronica Programable/Repositorios/Dominguez_2C_2025/firmware/projects/guia1_ej2
.SH SYNOPSIS
.br
.PP
.SS "Directorios"

.in +1c
.ti -1c
.RI "directorio \fBmain\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Este proyecto sirve como platilla para crear nuevos proyectos siguiendo el instructivo \fBProyecto Nuevo\fP\&. 
