.TH "C:/Users/carme/OneDrive/Desktop/cuarto/Electronica Programable/Repositorios/Dominguez_2C_2025/firmware/projects/guia1_ej2/main/guia1_ej2.c" 3 "guia1_ej2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/carme/OneDrive/Desktop/cuarto/Electronica Programable/Repositorios/Dominguez_2C_2025/firmware/projects/guia1_ej2/main/guia1_ej2.c
.SH SYNOPSIS
.br
.PP
\fR#include <stdio\&.h>\fP
.br
\fR#include <stdint\&.h>\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "void \fBapp_main\fP (void)"
.br
.in -1c
.SH "Documentación de funciones"
.PP 
.SS "void app_main (void )"

.PP
Definición en la línea \fB36\fP del archivo \fBguia1_ej2\&.c\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para guia1_ej2 del código fuente\&.
