.TH "C:/Users/carme/OneDrive/Desktop/cuarto/Electronica Programable/Repositorios/Dominguez_2C_2025/firmware/projects/1_blinking_switch_car/README.md" 3 "1_blinking_switch_car" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/carme/OneDrive/Desktop/cuarto/Electronica Programable/Repositorios/Dominguez_2C_2025/firmware/projects/1_blinking_switch_car/README.md
.SH SYNOPSIS
.br
.PP
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para 1_blinking_switch_car del código fuente\&.
