.TH "C:/Users/carme/OneDrive/Desktop/cuarto/Electronica Programable/Repositorios/Dominguez_2C_2025/firmware/projects/1_blinking_switch_car/build/esp-idf/mbedtls/mbedtls/library/version_features.c" 3 "1_blinking_switch_car" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/carme/OneDrive/Desktop/cuarto/Electronica Programable/Repositorios/Dominguez_2C_2025/firmware/projects/1_blinking_switch_car/build/esp-idf/mbedtls/mbedtls/library/version_features.c
.SH SYNOPSIS
.br
.PP
\fR#include 'common\&.h'\fP
.br

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para 1_blinking_switch_car del código fuente\&.
